quarkus.banner.enabled=false

quarkus.azure-functions.app-name=func-enterprise-app-secret-rotate

quarkus.log.console.format=%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} | context.invocationId=%X{context.invocationId} | %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.category."com.azure".level          =ERROR
quarkus.log.category."com.azure.identity".level =ERROR
quarkus.log.category."com.microsoft".level      =ERROR
quarkus.log.category."com.microsoft.azure".level=ERROR

# %test.quarkus.log.category."com.azure".level            =INFO
# %test.quarkus.log.category."com.azure.identity".level   =ERROR
# %test.quarkus.log.category."com.microsoft".level        =ERROR
# %test.quarkus.log.category."com.microsoft.azure".level  =ERROR


app.message.format.pattern.storage.account.blob.endpoint   = https://{0}.blob.core.windows.net/
app.message.format.pattern.storage.account.resource.group  = /subscriptions/{0}/resourceGroups/{1}
app.message.format.pattern.scope.storage.account           = {0}/providers/Microsoft.Storage/storageAccounts/{1}
app.message.format.pattern.scope.storage.account.container = {0}/providers/Microsoft.Storage/storageAccounts/{1}/blobServices/default/containers/{2}
