quarkus.azure-functions.app-name=func-keyvault-secret-rotation

quarkus.banner.enabled=false

quarkus.log.console.format                          = %d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} | context.invocationId=%X{context.invocationId} | %-5p [%c{3.}:%L] (%t) %s%e%n
quarkus.log.category."com.azure".level              = ERROR
quarkus.log.category."com.azure.identity".level     = ERROR
quarkus.log.category."com.microsoft".level          = ERROR
quarkus.log.category."com.microsoft.azure".level    = ERROR

%dev.quarkus.log.console.format                         = context.invocationId=%X{context.invocationId} | %-5p [%c{3.}:%L] (%t) %s%e%n
%dev.quarkus.log.category."com.azure".level             = ERROR
%dev.quarkus.log.category."com.azure.identity".level    = ERROR
%dev.quarkus.log.category."com.microsoft".level         = ERROR
%dev.quarkus.log.category."com.microsoft.azure".level   = ERROR
